# permissions for end users to view replicatedconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicatedconfigmap-viewer-role
rules:
- apiGroups:
  - rcm.aaronbatilo.dev
  resources:
  - replicatedconfigmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rcm.aaronbatilo.dev
  resources:
  - replicatedconfigmaps/status
  verbs:
  - get
