# permissions for end users to edit replicatedconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicatedconfigmap-editor-role
rules:
- apiGroups:
  - rcm.aaronbatilo.dev
  resources:
  - replicatedconfigmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rcm.aaronbatilo.dev
  resources:
  - replicatedconfigmaps/status
  verbs:
  - get
