FROM golang:1.13

# Versions
ARG OS=linux
ARG ARCH=amd64
ARG KUBEBUILDER_VERSION=2.3.0

# Install kubebuilder
WORKDIR /tmp
RUN curl -Lo kubebuilder.tar.gz https://go.kubebuilder.io/dl/${KUBEBUILDER_VERSION}/${OS}/${ARCH} \
      && tar -xzvf kubebuilder.tar.gz \
      && mv kubebuilder_${KUBEBUILDER_VERSION}_${OS}_${ARCH}/bin/kubebuilder /usr/local/bin/kubebuilder \
      && rm -rf kubebuilder*
