FROM ubuntu:18.04

# Versions
ARG OS=linux
ARG ARCH=amd64
ARG KUBEBUILDER_VERSION=2.3.0

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      curl=7.58.0-2ubuntu3.8 \
      ca-certificates=20180409 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install kubebuilder
WORKDIR /tmp
RUN curl -Lo kubebuilder.tar.gz https://go.kubebuilder.io/dl/${KUBEBUILDER_VERSION}/${OS}/${ARCH} \
      && tar -xzvf kubebuilder.tar.gz \
      && mv kubebuilder_${KUBEBUILDER_VERSION}_${OS}_${ARCH}/bin/kubebuilder /usr/local/bin/kubebuilder \
      && rm -rf kubebuilder*
